server:
  port: 80
  context-path: /
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 29
    password: redhat     # 密码（默认为空）
  datasource:
    name: mysql_druid
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yoyo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: XroRXpiGU7vJeuQrAnZ8FhA4+BEzU9x45IabHN5yzo8bNhm2VXcUG4XdMf1RxNP5CQmbRr05/S/bsNvOcnSaHA==
    sql-script-encoding: UTF-8
    druid:
      filter.config.enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALirgbRwt9we2+zKDMwEscyBxd901teyUNDexKpqEOMR943gmUhpBPCvqpZPp04KAxHkt612njXgjwJOAVm0kZECAwEAAQ==
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456