server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30

spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true
  redis:
      timeout: 15000ms  # 连接超时时长（毫秒）
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait:  -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5        # 连接池中的最小空闲连接
mybatis:
  #type-aliases-package: cn.hejinyo
  mapper-locations: classpath*:cn/hejinyo/jelly/modules/*/dao/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
    helperDialect: mysql
    page-size-zero: true
    reasonable: true
    params: pageNum=start;pageSize=limit;pageSizeZero=zero;reasonable=heli;count=contsql
    row-bounds-with-count: true

info:
  app:
    name: jelly
    version: 1.0