server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30

spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
  resources: # 指定静态资源的路径
      static-locations: classpath:/static/,classpath:/templates/
  aop:
    proxy-target-class: true
  redis:
      timeout: 15000ms  # 连接超时时长（毫秒）
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait:  -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5        # 连接池中的最小空闲连接
  mail:
    host: smtp.hejinyo.cn
    username: jelly@hejinyo.cn
    password: Redhat@2018
    default-encoding: utf-8
mybatis:
  #type-aliases-package: cn.hejinyo
  mapper-locations: classpath*:cn/hejinyo/jelly/modules/*/dao/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
    helperDialect: mysql
    page-size-zero: true
    reasonable: true
    params: pageNum=start;pageSize=limit;pageSizeZero=zero;reasonable=heli;count=contsql
    row-bounds-with-count: true

info:
  app:
    name: jelly
    version: 1.0

tencent:
  baseUrl: https://graph.qq.com
  authorizeURL: ${tencent.baseUrl}/oauth2.0/authorize
  accessTokenURL: ${tencent.baseUrl}/oauth2.0/token
  getUserInfoURL: ${tencent.baseUrl}/user/get_user_info
  getOpenIDURL: ${tencent.baseUrl}/oauth2.0/me
  clientId: 101494574
  clientSecret: 22e81b9bb632922b1095d0de329c9a35
  redirectURI: http://test.hejinyo.cn/api/oauth/v2
  scope: get_user_info
